name: Moderation4u
main: fr.lightnew.Moderation4u
version: Beta
api-version: 1.16
author: Lightnew
description: Plugin by Lightnew -> https://github.com/lightnew10
depend: [ Core ]
commands:
  tban:
    aliases:
      - ban
      - tempban
    permission: advanced.staff
  unban:
    permission: advanced.staff
  mute:
    permission: advanced.staff
  unmute:
    permission: advanced.staff
  fly:
    permission: base.staff
  freeze:
    permission: base.staff
  invsee:
    permission: base.staff
  kick:
    permission: base.staff
  reports:
    permission: base.staff
  report:
    aliases:
      - rep
  moderation:
    permission: base.staff
    aliases:
      - mod
